In [1]:
list1=[30,40,44,55,67]

In [2]:
type(list1)

list

In [3]:
len(list1)

5

In [4]:
list1.append(77)
list1

[30, 40, 44, 55, 67, 77]

In [5]:
list2=[11,22,33,66]
list1.extend(list2)
list1

[30, 40, 44, 55, 67, 77, 11, 22, 33, 66]

In [6]:
list1.insert(4,60)
list1

[30, 40, 44, 55, 60, 67, 77, 11, 22, 33, 66]

In [7]:
list1.remove(55)
list1

[30, 40, 44, 60, 67, 77, 11, 22, 33, 66]

In [8]:
list1.pop(5)
list1

[30, 40, 44, 60, 67, 11, 22, 33, 66]

In [9]:
list1.clear()
list1

[]

In [10]:
list1=[30,40,44,55,67,55,30]

In [11]:
list1.index(44)

2

In [12]:
list1.count(55)

2

In [13]:
list1.sort()
list1

[30, 30, 40, 44, 55, 55, 67]

In [14]:
list1.reverse()
list1

[67, 55, 55, 44, 40, 30, 30]

In [15]:
tuple1=('Rajesh','Rohan','Sumit')

In [16]:
tuple1[1]='Naveen'
tuple1
### as tuple is immutable, we cannot add, delete or replace any data in pre-defined tuple 

TypeError: 'tuple' object does not support item assignment

In [ ]:
set1={22,45,67,67,80,80,96}
set1

In [17]:
import pandas as pd
import re

In [18]:
dict1={'name':['Arun','Sunil','Deepak','Ramesh'],'age':[22,23,24,46],'city':['Bangalore','Mysore','Bidar','Chennai']}
dict1

{'name': ['Arun', 'Sunil', 'Deepak', 'Ramesh'],
 'age': [22, 23, 24, 46],
 'city': ['Bangalore', 'Mysore', 'Bidar', 'Chennai']}

In [19]:
df1=pd.DataFrame(dict1)
df1

,name,age,city
0,Arun,22,Bangalore
1,Sunil,23,Mysore
2,Deepak,24,Bidar
3,Ramesh,46,Chennai


In [20]:
df1.update({'age':[12,13,14,16]})
df1

,name,age,city
0,Arun,12,Bangalore
1,Sunil,13,Mysore
2,Deepak,14,Bidar
3,Ramesh,16,Chennai


In [21]:
dict2=dict1.copy()
dict2

{'name': ['Arun', 'Sunil', 'Deepak', 'Ramesh'],
 'age': [22, 23, 24, 46],
 'city': ['Bangalore', 'Mysore', 'Bidar', 'Chennai']}

In [22]:
dict2.setdefault('email',['arun1@gmail.com','sun34@yahoo.com','dee4@gmail.com','rameshj@gmail.com'])
dict2

{'name': ['Arun', 'Sunil', 'Deepak', 'Ramesh'],
 'age': [22, 23, 24, 46],
 'city': ['Bangalore', 'Mysore', 'Bidar', 'Chennai'],
 'email': ['arun1@gmail.com',
  'sun34@yahoo.com',
  'dee4@gmail.com',
  'rameshj@gmail.com']}

In [23]:
df2=pd.DataFrame(dict2)
df2

,name,age,city,email
0,Arun,22,Bangalore,arun1@gmail.com
1,Sunil,23,Mysore,sun34@yahoo.com
2,Deepak,24,Bidar,dee4@gmail.com
3,Ramesh,46,Chennai,rameshj@gmail.com


In [25]:
age=int(input('Enter the age:'))
if age<18:
    print('Not eligible to vote')
else:
    print('Eligible to vote')


Enter the age: 19


Eligible to vote


In [26]:
marks=int(input('Enter the marks:'))
if marks>=90:
    print('Scored grade A')
elif(marks>=75):
    print('Scored grade B')
elif(marks>=50):
    print('Scored grade C')
else: 
    print('Failed')

Enter the marks: 75


Scored grade B


In [27]:
import numpy as np

In [28]:
scalar_array=np.array(5)
scalar_array

array(5)

In [29]:
scalar_array.size

1

In [30]:
type(scalar_array)

numpy.ndarray

In [31]:
one_dim=np.array([1,2,3,4,5])
one_dim

array([1, 2, 3, 4, 5])

In [32]:
one_dim.size

5

In [33]:
one_dim.ndim

1

In [34]:
val=np.array(range(10,61,10))
val

array([10, 20, 30, 40, 50, 60])

In [35]:
## to create 2D array
two_d_array=(val[:3],val[3:6])
two_d_array

(array([10, 20, 30]), array([40, 50, 60]))

In [36]:
two_dim=np.random.randint(0,101,16).reshape(4,4)
two_dim

array([[48, 71, 15, 33],
       [ 3, 65, 49, 10],
       [12, 57, 56, 10],
       [36, 15, 48, 78]], dtype=int32)

In [37]:
two_d_arr=np.array([[2,3,4],[6,7,8],[10,17,19]])
two_d_arr


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 17, 19]])

In [66]:
new_arr=pd.DataFrame(two_d_arr)
new_arr

,0,1,2
0,2,3,4
1,6,7,8
2,10,17,19


In [68]:
df = pd.DataFrame(two_d_arr, columns=['A', 'B', 'C'])
df

,A,B,C
0,2,3,4
1,6,7,8
2,10,17,19


In [106]:
dict1={'Name':['A','B','C','D','E','F','G','H','I','J'],'Age':[22,24,26,28,24,25,27,23,21,30],
       'City':['Bangalore','Bidar','Chennai','Delhi','Mumbai','Pune','Jaipur','Gwalior','Pune','Bidar'],
       'Salary':[2000,1000,4000,None,4000,3000,None,5000,1500,3000]}
dict1

{'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
 'Age': [22, 24, 26, 28, 24, 25, 27, 23, 21, 30],
 'City': ['Bangalore',
  'Bidar',
  'Chennai',
  'Delhi',
  'Mumbai',
  'Pune',
  'Jaipur',
  'Gwalior',
  'Pune',
  'Bidar'],
 'Salary': [2000, 1000, 4000, None, 4000, 3000, None, 5000, 1500, 3000]}

In [107]:
df=pd.DataFrame(dict1)
df

,Name,Age,City,Salary
0,A,22,Bangalore,2000.0
1,B,24,Bidar,1000.0
2,C,26,Chennai,4000.0
3,D,28,Delhi,NaN
4,E,24,Mumbai,4000.0
5,F,25,Pune,3000.0
6,G,27,Jaipur,NaN
7,H,23,Gwalior,5000.0
8,I,21,Pune,1500.0
9,J,30,Bidar,3000.0


In [108]:
df.loc[7]=['A', 22,'Bangalore',2000]
df

,Name,Age,City,Salary
0,A,22,Bangalore,2000.0
1,B,24,Bidar,1000.0
2,C,26,Chennai,4000.0
3,D,28,Delhi,NaN
4,E,24,Mumbai,4000.0
5,F,25,Pune,3000.0
6,G,27,Jaipur,NaN
7,A,22,Bangalore,2000.0
8,I,21,Pune,1500.0
9,J,30,Bidar,3000.0


In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [110]:
df[['Name','City']]

,Name,City
0,A,Bangalore
1,B,Bidar
2,C,Chennai
3,D,Delhi
4,E,Mumbai
5,F,Pune
6,G,Jaipur
7,A,Bangalore
8,I,Pune
9,J,Bidar


In [111]:
df.drop(columns='City')

,Name,Age,Salary
0,A,22,2000.0
1,B,24,1000.0
2,C,26,4000.0
3,D,28,NaN
4,E,24,4000.0
5,F,25,3000.0
6,G,27,NaN
7,A,22,2000.0
8,I,21,1500.0
9,J,30,3000.0


In [112]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    2
dtype: int64

In [113]:
df.duplicated().sum()

np.int64(1)

In [122]:
sal_mean=df['Salary'].mean()
sal_mean

np.float64(2562.5)

In [128]:
new_Sal=df.fillna(sal_mean, inplace=True)
new_Sal

In [129]:
df.drop_duplicates()

,Name,Age,City,Salary
0,A,22,Bangalore,2000.0
1,B,24,Bidar,1000.0
2,C,26,Chennai,4000.0
3,D,28,Delhi,2562.5
4,E,24,Mumbai,4000.0
5,F,25,Pune,3000.0
6,G,27,Jaipur,2562.5
8,I,21,Pune,1500.0
9,J,30,Bidar,3000.0
